import Head from 'next/head'
import styles from '../styles/Home.module.css'
import YandexMap from '/features/maps/YandexMap.jsx'
import Header from '/features/header'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Гильдия Юристов</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
        <YandexMap />
    </div>
  )
}