import Head from 'next/head'
import YandexMap from '/features/maps/YandexMap.jsx'
import Header from '/features/header'
import React from 'react'
import {Box } from "@chakra-ui/react"

const Layout = props => (
  <>
		<Head>
        <title>Гильдия Юристов</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
		</Head>
		<Header />
    <Box>
      {props.children}
    </Box>
    <YandexMap />
  </>
);

export default Layout;